{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-main-servicemonitor
  labels:
    app: {{ .Release.Name }}
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: prometheus
  endpoints:
  - port: http
    path: /metrics

---
{{- if .Values.canary.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-canary-servicemonitor
  labels:
    app: {{ .Release.Name }}-canary
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-canary
      release: prometheus
  endpoints:
  - port: http
    path: /metrics
{{- end }}
{{- end }}